### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by billyquith** [RegretBomb/ComponentPool#1]
I have my own simple component object system and am interested in cache coherency. Currently I'm just heap allocating everything, but plan to [use pools](https://github.com/billyquith/MemoryPool) (much faster allocation and memory usage efficiency), but then you are iterating over the data in a random order.

I wondered what you learnt from the project, or if abandoned, why so? The [other reference](http://www.insomniacgames.com/a-dynamic-component-architecture-for-high-performance-gameplay/) I have for this is the Insomniac guys.

**Comment by BlamKiwi** [comment]
The projects abandoned in the sense I only worked on it as a learning exercise when I was a bit green in engine design/C++. I sometimes refer back to it. 
- You need to amortise deletes or introduce the concept of a bulk delete/sleep/wake. The object swapping in the negative case for a large pool almost looks like a GC pause in a profiler.
- Making this data structure thread safe will be hard, although you could do it with read/writer locks in principle. 
- I'm not entirely sure the ComponentReference is bug free. I would probably use a handles next time as they are far simpler than smart pointers. 
- The cache coherency of the pseudo stack layout is real. Although I would maybe think about the strategy a little more carefully.
- The pool as a piece of Architecture fundamentally limits the Structs of Arrays layout optimisation, which is probably a deal breaker for any serious engine work. Although I have seen SoA engines that do a similar thing to this pool.
